### ISSUE TITLE
javinator website/subdomains down

### ISSUE THREAD

**Issue by Firesphere** [Javinator9889/Discord-PPA#15]
Including the PPA, all return a CF error :'(

**Comment by notfixingit3** [comment]
second this, still down

**Comment by Javinator9889** [comment]
I'm able to access everything. Could you attach any screenshot or proof?

**Comment by notfixingit3** [comment]
its working now, if it happens again, I'll SS it

**Comment by Firesphere** [comment]
What @notfixingit3 says :)

p.s.
Nice ironically applicable name there, by the way :laughing:
