### ISSUE TITLE
Keyoutdated

### ISSUE THREAD

**Issue by Xdavius** [Javinator9889/Discord-PPA#16]
Hi,

Please consider updating the blog with updated key :

 ```--recv-keys A2A43BD5139A4173```

Regards

**Comment by Javinator9889** [comment]
The key hasn't changed, it must be the same.

**Comment by Xdavius** [comment]
> The key hasn't changed, it must be the same.

The one I give you upper works. But it's not the key on your blog.

This one is on your blog : 08633B4AAAEB49FC


https://blog.javinator9889.com/discord-ppa-keep-it-up-to-date-on-linux-easily/

```sudo -E gpg --no-default-keyring --keyring=/usr/share/keyrings/javinator9889-ppa-keyring.gpg --keyserver keyserver.ubuntu.com --recv-keys 08633B4AAAEB49FC```

**Comment by Javinator9889** [comment]
I tried with a newly created VM and the commands I wrote work just fine. If I'm not wrong, the key you described is the fingerprint of the imported key, but references the same.

If you check Ubuntu keyserver, you'll see they are exactly the same keys:
* https://keyserver.ubuntu.com/pks/lookup?search=08633B4AAAEB49FC&fingerprint=on&op=index
* https://keyserver.ubuntu.com/pks/lookup?search=A2A43BD5139A4173&fingerprint=on&op=index
