### ISSUE TITLE
File has unexpected size (782 != 781). Mirror sync in progress? [IP: 188.114.97.2 443]

### ISSUE THREAD

**Issue by KaKi87** [Javinator9889/Discord-PPA#18]
Hi,

I'm getting the following error on `sudo apt update` :

```
Get:15 https://ppa.javinator9889.com all/main amd64 Packages [781 B]                                                                                                       
Err:15 https://ppa.javinator9889.com all/main amd64 Packages                                                                                                                    
  File has unexpected size (782 != 781). Mirror sync in progress? [IP: 188.114.97.2 443]
  Hashes of expected file:
   - Filesize:781 [weak]
   - SHA256:b9807ec0fc616b94a8cb3b88e83efd0466cc649553f7111572eb05a9e79b3ac8
   - SHA1:abee9966b7d6b550d8de5f0a05d158141ce0680c [weak]
   - MD5Sum:fac2257a3fd7ac491bc48b3de257aa3a [weak]
  Release file created at: Tue, 09 Apr 2024 17:27:42 +0000
```

The only way to bypass it was to remove the PPA.

Thanks

**Comment by Javinator9889** [comment]
As it can be read, the mirror was synchronizing

**Comment by KaKi87** [comment]
Well, that seemed unlikely since the error message indicated a 1 byte difference and that the time indicated was 45 minutes ago. Thanks

**Comment by KaKi87** [comment]
Hum, actually, the error is still occuring, so whatever *synchronizing* means, it's either still doing it or it's something else. Thanks

**Comment by Javinator9889** [comment]
@KaKi87 try removing the APT list and adding it again. Sometimes APT messes up with cache and breaks the installation if it was just during the mirror synchronization.

**Comment by KaKi87** [comment]
As mentioned, after removing the PPA, `sudo apt update` runs okay.

However, when adding it back, the same error occurs again.

Thanks

**Comment by Javinator9889** [comment]
I cannot reproduce your issue @KaKi87 - I've just created a new VM and it ran smoothly. Please, check the steps you've done and try doing it again. Issue the uninstall commands and then the install ones again.

Sorry not being able to help you better.

**Comment by Mubelotix** [comment]
Same here

```
E: Failed to fetch https://ppa.javinator9889.com/dists/all/main/binary-amd64/Packages.gz  File has unexpected size (510 != 508). Mirror sync in progress? [IP: 188.114.97.11 443]
   Hashes of expected file:
    - Filesize:508 [weak]
    - SHA256:04da2a95aebfce375d16f68ca5133cb1462b951bfa4e93ac2c8db87127756fb8
    - SHA1:9ec9876e1931f6e2c23c52a43a9c9b6e78f421d2 [weak]
    - MD5Sum:35f2613e13087cd416be62c52a01ff23 [weak]
   Release file created at: Mon, 16 Jun 2025 21:13:40 +0000
```

It had been working for years

**Comment by Javinator9889** [comment]
As you can read, mirror sync is in progress. Just give it a couple of minutes

**Comment by Mubelotix** [comment]
> As you can read, mirror sync is in progress. Just give it a couple of minutes

You were right, thank you again
