### ISSUE TITLE
PPA/Website down

### ISSUE THREAD

**Issue by dtrunk90** [Javinator9889/Discord-PPA#19]
javinator9889.com is giving a timeout

**Comment by Frozen-byte** [comment]
I confirm, `javinator9889.com` does time out.

**Comment by Totto16** [comment]
has [launchpad.net](https://launchpad.net) an API or something of that sort, where the script could upload it instead of hosting a repo somewhere 🤔

**Comment by Javinator9889** [comment]
There's an ongoing issue with the electricity provider. All servers are down. This can be tracked through https://status.javinator9889.com

I'll ping here once everything is OK. Sorry for the inconvenience.

**Comment by Totto16** [comment]
No worries man, you provide us with this repo, thank you for that ❤️

**Comment by dtrunk90** [comment]
It's up and running again.

**Comment by Javinator9889** [comment]
Thanks everyone for reporting and your support 😊
