### ISSUE TITLE
Kubuntu 24.04 - File has unexpected size (517 != 516). 

### ISSUE THREAD

**Issue by dm2912** [Javinator9889/Discord-PPA#21]
Error today in Kubuntu 24.04 when doing apt update

```
E: Failed to fetch https://ppa.javinator9889.com/dists/canary/main/binary-amd64/Packages.gz  File has unexpected size (517 != 516). Mirror sync in progress? [IP: 104.21.91.51 443]
   Hashes of expected file:
    - Filesize:516 [weak]
    - SHA256:7b5b9ebed0b844c94abcab87874ca68ce3db4a7c2a01c0b8c1680d146552a858
    - SHA1:9c1045e9ba886d94cf22a0c95a457abf071cbe95 [weak]
    - MD5Sum:906d88f7e86530a2dcbf9a18a00039d7 [weak]
   Release file created at: Tue, 21 May 2024 20:23:39 +0000
```

**Comment by N0rdmann** [comment]
**Mhm was there a fix to this?**
Experiencing the same right now on Mint 22 (Ubuntu 24.04)

```
E: Fehlschlag beim Holen von https://ppa.javinator9889.com/dists/all/main/binary-amd64/Packages.gz Datei hat eine unerwartete Größe (510 != 509). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 188.114.97.3 443]
   Hashes of expected file:
    - Filesize:509 [weak]
    - SHA256:c740d96eb628498625ec9cfd8d788c2e18e3300908c70f5b4a7d9d01a0840631
    - SHA1:80724afc3e1545da3ebba7e42d77903840508376 [weak]
    - MD5Sum:6de78e268db7c8b876cad068eb69cdff [weak]
   Release file created at: Mon, 18 Nov 2024 18:06:51 +0000
```

**Comment by N0rdmann** [comment]
ok so there was an discord update today and the ppa packages.gz seems fine just now - which defeats the whole purpose of this:
you cannot start the outdated Discord version anymore
but cannot update it in time when you want to run it as per the apt error

**Comment by Javinator9889** [comment]
As it can be read, the mirror sync was in progress

**Comment by N0rdmann** [comment]
Yeah but lasting THAT long? Is there something hanging on server side or a way to improve this time?
As mentioned, this "wait-time" defeats any benefit of this PPA since you cannot start Discord once it finds itself outdated - but then the apt update isn't possible due to Mirror sync error, so downloaded the deb manually again to get into my discord call in time...
