### ISSUE TITLE
Keyserver receive failed 

### ISSUE THREAD

**Issue by rehhouari** [Javinator9889/Discord-PPA#3]
The key needs updating again I think:

```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 08633B4AAAEB49FC
Executing: /tmp/apt-key-gpghome.O6IFOLGPCj/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 08633B4AAAEB49FC
gpg: keyserver receive failed: Server indicated a failure

```
> 
> Hi,
> 
> This is very probably because of the key: the server was migrated so the key changed.
> 
> Please, try removing the old key
> `sudo apt-key del 5890E288F7ED6702`
> 
> and adding the new one:
> `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 08633B4AAAEB49FC`
> 
> Then, do an `sudo apt-get update` and `sudo apt-get install discord`.
> 
> Please, keep me updated with any changes and/or errors you may have
> 
> _Originally posted by @Javinator9889 in https://github.com/Javinator9889/Discord-PPA/issues/1#issuecomment-739144740_

**Comment by rehhouari** [comment]
as a temporary fix added `[trusted=yes]` to the `source.list` line

**Comment by Javinator9889** [comment]
Hi, 

Very probably there was a one-time issue with Ubuntu keyser west, as I executed it from my phone and it worked as expected:
![Screenshot_20210418-073127.jpg](https://user-images.githubusercontent.com/25952165/115135367-558e9900-a018-11eb-807d-e52b156196e8.jpg)

In addition I didn't changed the keys so there is no need to update something.

Please, have a look and let me know if you managed to solve your error.

**Comment by rehhouari** [comment]
Yes it is working now, thanks for maintaining this ^^
