### ISSUE TITLE
Discord Canary support

### ISSUE THREAD

**Issue by jackmawer** [Javinator9889/Discord-PPA#4]
Discord Canary builds are also available for discord as deb files. It would be fantastic if this PPA also provided Canary builds.
The deb files can be found at https://discordapp.com/api/download/canary?platform=linux

I would help implement this myself but I don't understand PPA creation well enough to set up reprepro - if you have any guides on how this works, that would also be much appreciated.

**Comment by Javinator9889** [comment]
Definetly it can be useful for some users, so will have a look and tell you more whether I decide to implement it or not. Thanks for the issue

**Comment by Javinator9889** [comment]
At commit 38ed27aa the canary repository was included at the PPA. You can add such source by using:

```
deb [arch=amd64 signed-by=/usr/share/keyrings/javinator9889-ppa-keyring.gpg] https://ppa.javinator9889.com canary main
```

and then install it with:

```
sudo apt install discord-canary
```
